# Generated by Django 4.2.5 on 2023-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
