# Generated by Django 4.2.5 on 2023-10-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0002_alter_member_member_id'),
    ]

    operations = [
    ]
