# Generated by Django 4.2.5 on 2023-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0005_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.CharField(max_length=50),
        ),
    ]
