# Generated by Django 4.2.5 on 2023-10-18 17:33

from django.db import migrations
from InfoHaven_App.models import User, Member

def create_member_for_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # Get the User model
    for user in User.objects.all():
        # Check if a Member instance already exists for this User
        if not Member.objects.filter(user=user).exists():
            Member.objects.create(user=user)

class Migration(migrations.Migration):


    dependencies = [
        ('InfoHaven_App', '0009_alter_member_user'),
    ]

    operations = [
        migrations.RunPython(create_member_for_users),
    ]