# Generated by Django 4.2.5 on 2023-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0010_auto_20231019_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, to='InfoHaven_App.book'),
        ),
    ]
