# Generated by Django 4.2.5 on 2023-10-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0012_remove_member_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
