# Generated by Django 4.2.6 on 2023-10-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0013_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('Record_ID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoHaven_App.member')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoHaven_App.book')),
            ],
        ),
    ]
