# Generated by Django 4.2.5 on 2023-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0014_borrowingrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='borrowed_books',
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
