# Generated by Django 4.2.6 on 2023-11-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0016_alter_borrowingrecord_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='date_borrowed',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='date_returned',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='isReturned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='return_date',
            field=models.DateField(default=None),
        ),
    ]
