# Generated by Django 4.2.6 on 2023-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0017_borrowingrecord_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
