# Generated by Django 4.2.5 on 2023-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0019_borrowingrecord_money_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingrecord',
            name='money_penalty',
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
