# Generated by Django 4.2.5 on 2024-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0021_alter_book_isbn_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
