# Generated by Django 4.2.5 on 2024-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0022_borrowingrecord_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='isRequested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
