# Generated by Django 4.2.5 on 2024-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoHaven_App', '0023_borrowingrecord_isrequested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='isAccepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='isRequested',
            field=models.IntegerField(default=0),
        ),
    ]
